[build]
    publish = "dist"
    command = "yarn run build"
    node_bundler = "esbuild"

[dev]
    publish = "src"
    command = "yarn run dev"
    targetPort = 5173
    node_bundler = "esbuild"

[functions]
  node_bundler = "esbuild"
