name: Lint the code
on:
  push:
    branches:
      - "**"
  pull_request:
    branches:
      - "**"
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: oven-sh/setup-bun@v2
    - name: Install modules
      run: bun install
    - name: Run ESLint
      run: bun lint
